


---
title: "Challenge 3 "
author: "Benjamin Knaack"
date: "`r Sys.Date()`"
output: html_document
---





#### 1. Compensation Features
What can you deduce about the interaction between Monthly Income and Attrition?

c. Those that are leaving have a lower Monthly Income


#### 2. Compensation Features
What can you deduce about the interaction between Percent Salary Hike and Attrition?

d. It's difficult to deduce anything based on the visualization. 
... but rather c than a or b.

#### 3. Compensation Features
What can you deduce about the interaction between Stock Option Level and Attrition?

b. Those that are staying have a higher stock option level

#### 4. Survey Results
What can you deduce about the interaction between Environment Satisfaction and Attrition?

a. A higher proportion of those leaving have a low environment satisfaction level
  
#### 5. Survey Results
What can you deduce about the interaction between Work Life Balance and Attrition

b. Those that are staying have a higher density of 2's and 3's

#### 6. Performance Data
What Can you deduce about the interaction between Job Involvement and Attrition?

a. Those that are leaving have a lower density of 3's and 4's

#### 7. Work-Life Features
What can you deduce about the interaction between Over Time and Attrition?

a. The proportion of those leaving that are working Over Time are high compared to those that are not leaving

#### 8. Training and Education
What can you deduce about the interaction between Training Times Last Year and Attrition

b. People that leave tend to have less annual trainings

#### 9. Time-Based Features
What can you deduce about the interaction between Years At Company and Attrition

b. People that leave tend to have less working years at the company

#### 10. Time-Based Features
What can you deduce about the interaction between Years Since Last Promotion and Attrition?

c. It's difficult to deduce anything based on the visualization
... but rather b than a.
