project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "CHALLENGE ONE"
            file: content/01_journal/01_challenge.qmd
          - text: "CHALLENGE TWO"
            file: content/01_journal/02_challenge.qmd
          - text: "CHALLENGE THREE"
            file: content/01_journal/03_challenge.qmd
          - text: "CHALLENGE FOUR"
            file: content/01_journal/04_challenge.qmd
          - text: "CHALLENGE FIVE"
            file: content/01_journal/05_challenge.qmd
          - text: "CHALLENGE SIX"
            file: content/01_journal/06_challenge.qmd

      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto